# Generated by Django 5.2.1 on 2025-06-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('preferencia_notificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=50)),
                ('vehiculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Despachador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquetes_totales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DurationField()),
                ('entrego_todos', models.BooleanField()),
                ('vueltas', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.admin')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_e', models.DateField()),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('en bodega', 'En bodega'), ('en camino', 'En camino'), ('entregado', 'Entregado')], max_length=20)),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('puntos_referencia', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=100)),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.informe')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ruta'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.conductor')),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.despachador')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.envio')),
            ],
            options={
                'unique_together': {('despachador', 'conductor', 'envio')},
            },
        ),
    ]
